services:
  dns-updater:
    image: public-dns-updater:latest
    environment:
      Providers__TransIP__Domains__0: example.com
      Providers__TransIP__Username: ExampleUser
      Providers__TransIP__PrivateKey: |
        -----BEGIN PRIVATE KEY-----
        thisisasecretprivatekey
        -----END PRIVATE KEY-----
